name: 'Sphinx Build'
description: 'Builds documentation using Sphinx'
author: 'Ammar Askar'
branding:
  icon: 'book'
  color: 'blue'
inputs:
  repo-token:
    description: 
      The GITHUB_TOKEN secret.
      Set to "${{{{ secrets.GITHUB_TOKEN }}}}" for status check with in-line
      warnings and errors.
  build-command:
    description:
      The command used to build your documentation (defaults to `make html`)
    required: false
    default: make html
runs:
  using: 'docker'
  image: 'Dockerfile'