name: 'Sphinx Build'
description: 'Builds documentation using Sphinx'
author: 'Ammar Askar'
branding:
  icon: 'book'
  color: 'blue'
inputs:
  docs-folder:
    description:
      The folder containing your sphinx docs.
    required: true
    default: "docs/"
  repo-token:
    description: 
      The GITHUB_TOKEN secret.
      Needed for status check with in-line warnings and errors. Check out the
      full README to see how to fill this.
  build-command:
    description:
      The command used to build your documentation.
    required: false
    default: make html
  pre-build-command:
    description:
      Run before the build command, you can use this to install system level
      dependencies, for example with
      "apt-get update -y && apt-get install -y perl"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'